version: "3.1"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080